// Type definitions for the MarzPay client surface injected by the plugin at
// `ctx.state.marzpay`. The plugin client IS the integration boundary; these
// types describe the subset of its verified, published API that the demo
// consumes. They contain no implementation — the plugin owns all network I/O.

/** Input to a mobile-money collection. */
export interface CollectMoneyInput {
  amount: number; // 5000
  country: string; // "UG"
  reference: string; // unique Reference generated by checkout
  phone_number: string; // customer MSISDN (mobile money)
}

/**
 * `collections.collectMoney` result. For mobile money no `redirectUrl` is
 * returned; `redirectUrl` is present only for the card method.
 */
export interface CollectMoneyResult {
  reference: string;
  status: string;
  redirectUrl?: string;
}

/** `collections.getStatus(reference)` — authoritative completion check. */
export interface StatusResult {
  reference: string;
  status: string;
}

/** `transactions.get(reference)` — confirmed amount/currency/status. */
export interface TransactionResult {
  id: string;
  reference: string;
  amount: number;
  currency: string; // e.g. "UGX"
  status: string;
}

/** The subset of the plugin client surface this demo consumes. */
export interface MarzPayClient {
  collections: {
    collectMoney(input: CollectMoneyInput): Promise<CollectMoneyResult>;
    getStatus(reference: string): Promise<StatusResult>;
  };
  transactions: {
    get(reference: string): Promise<TransactionResult>;
  };
  validateWebhook(rawBody: string, signature: string): boolean;
  utils: {
    isValidPhoneNumber(value: string): boolean;
    formatPhoneNumber(value: string): string;
  };
}
